prevent user from deleting themselves as last admin
erskingardner/keycast pull request #2
Opened 2024-12-26 17:01 UTC by felixzieger

2024-12-26 20:03 UTC, erskingardner requested changes
Thanks for the contribution @felixzieger  - one small change to improve the way we're querying for the count.

2024-12-26 20:03 UTC, erskingardner commented on api/src/api/http/teams.rs
> +        let remaining_admin_count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM team_users WHERE team_id = ?1 AND user_public_key != ?2 AND role = 'admin'")
Can we use `query_scalar` here instead so that we don't end up with a tuple result that we then have to use `.0` on? 

```rust
let remaining_admin_count = sqlx::query_scalar("SELECT COUNT(*) FROM team_users WHERE team_id = ?1 AND user_public_key != ?2 AND role = 'admin'")
    .bind(team_id)
    .bind(removed_user_public_key.to_hex())
    .fetch_one(&mut *tx)
    .await?;

if remaining_admin_count == 0 {
...
```

2024-12-27 00:43 UTC, felixzieger commented on api/src/api/http/teams.rs
> +        let remaining_admin_count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM team_users WHERE team_id = ?1 AND user_public_key != ?2 AND role = 'admin'")
Makes sense! I switched to query_scalar

2024-12-27 07:19 UTC, erskingardner approved these changes

2024-12-27 07:19 UTC, merged